<h1>What is Brovine Used For?</h1>
<p>Brovine is used by the Animal Science department at Cal Poly to catalog and analyze genetic information. To give a brief overview of the scope of the problem the researchers, led by Dan Peterson, are attempting to solve, we first discuss the biology of the processes they are studying.

<h2>Introduction</h2>
<p>Physiological function in multicellular organisms requires different cells to have different specific functions and characteristics, and the attainment of these specialized characteristics is called differentiation. Differentiation is achieved in part when proteins, called "transcription factors" interact with regions of DNA called "promoter regions." When transcription factors bind to the promoter regions of DNA, the transcription of the gene is "activated," which essentially means that the gene is expressed in the cell. Differentiation involves a myriad of regulatory events that lead to structural and functional organization of the genome to allow expression and regulation of the appropriate set of proteins for the specialized functions of that cell type.</p>

<p>Proteins are made up of amino acids, whose order is determined by a sequence of nucleotides in DNA. The proteins that characterize a cell's phenotype are strings of amino acids bound together whose order is coded by the sequence of nucleotides in a messenger RNA (mRNA) that is transcribed from DNA in the nucleus. The process of transcription (production of the mRNA from DNA sequence) of these protein coding genes is regulated in part by the interaction of regulatory proteins called transcription factors (TF) with specific sequences (called regulatory elements) within a region of DNA adjacent to the protein coding gene called the promoter (Figure 1).</p>

<div class="img-left">
   <img src="/images/promoter-region.png" alt="Figure 1: Schematic showing the promoter region of a gene with three regulatory elements (RE) each bound by their respective transcription factor (TF) contributing to the activation of transcription of the gene." />
   <p class="img-desc"><strong>Figure 1:</strong> Schematic showing the promoter region of a gene with three regulatory elements (RE) each bound by their respective transcription factor (TF) contributing to the activation of transcription of the gene.</p>
</div>

<p>Understanding the regulatory events that lead to differentiation of different cell types is a critical step in understanding normal biological function as well as understanding what errors underlie dysfunctions such as cancer. The researchers have been studying the differentiation of mammary epithelial cells by identifying a subset of the proteins whose abundance changes during the transition from a mammary precursor to a functional mammary cell. The promoter region of each of the genes coding for these proteins has been analyzed to identify many potential regulatory elements (hundreds) that may have contributed to their differential expression. It is likely that few, if any, of these elements were actually involved, making critical analysis of the probability of their involvement very important. The sheer number of potential elements makes analysis "by hand" impractical, and is the reason for constructing a searchable database.</p>

<h2>How Experiments are Performed</h2>
<p>Dr. Peterson's approach is to study what changes occur in mammary cells from different sources during the transformation from one state to another state (e.g. pregnancy to lactation in mice, or undifferentiated to differentiated in the MAC-T bovine cell line). This is done by comparing global protein expression in the two states and identifying a subset of the proteins that change in abundance with the transformation from one state to the other. The data that we will begin with is from a cell line (MAC-T) from one species (cow, or "bovine"). For each species, we will also be including more than one comparison based on the different sources of cells we are comparing. For example, within the murine species, we will be comparing pregnant to lactating, nonpregnant to pregnant, and undifferentiated to differentiated HC11 cell line (3 separate comparisons). In the figure below, each arrow corresponds to a comparison. From each comparison, we generate a list of proteins that change in abundance as well as their direction and magnitude of change (though we are not including magnitude in our database).</p>

<img src="/images/comparisons.png" alt="Figure 2: Several types of differentiation (cell transforming from one type to another) that will be used" />

<p><strong>The gene promoters</strong>: Remember that each protein is the result of a gene being "expressed", and that the gene expression is regulated in part by sequences in the gene promoter interacting with activating proteins or "factors". Once the list of proteins that changed in abundance (up or down) in our comparison is obtained, the database is searched for the gene for each protein in a genome database and find its promoter sequence. We then copy 2000 bases of that promoter sequence for analysis of the sequence to identify potential regulatory sequence elements within the 2000 base sequence.</p>
<p><strong>Regulatory sequence search (TESS)</strong>: We use an online program called Transcription Element Search System (TESS) that analyzes our input DNA sequence (the 2000 base promoter) and identifies short sequences that have been shown somewhere before to interact with a transcription factor to activate gene expression. The results of this search can be downloaded in a Microsoft Excel for each gene promoter that we used as a query. These Excel documents are the documents that are inserted into Brovine for analysis. To learn more about these Excel files, view the PDF linked to at the bottom of this page.</p>

<p>This is an excerpt of <a href="/files/project-goals.pdf">the project overview [PDF]</a> written by Dan Peterson.</p>
